### ISSUE TITLE
Providers fail to provide after Android build

### ISSUE THREAD

**Issue by rhysp** [mfav/syrinj#1]
Providers would occasionally fail to inject and "provide" in the Unity editor when testing my game. The console would be filled with errors such as:

```
[PlayerTouchRegion (PlayerDrag)] Could not find provider for player
UnityEngine.Debug:LogError(Object)
Syrinj.DependencyContainer:TryInjectProvidable(Injectable) (at Assets/Syrinj/Scripts/DependencyContainer.cs:113)
Syrinj.DependencyContainer:TryInjectAll() (at Assets/Syrinj/Scripts/DependencyContainer.cs:92)
Syrinj.DependencyContainer:Inject(IList`1) (at Assets/Syrinj/Scripts/DependencyContainer.cs:64)
Syrinj.GameObjectInjector:Inject() (at Assets/Syrinj/Scripts/GameObjectInjector.cs:35)
Syrinj.SceneInjector:InjectBehaviours(MonoBehaviour[]) (at Assets/Syrinj/Scripts/SceneInjector.cs:41)
Syrinj.SceneInjector:InjectScene() (at Assets/Syrinj/Scripts/SceneInjector.cs:29)
Syrinj.SceneInjector:Awake() (at Assets/Syrinj/Scripts/SceneInjector.cs:17)
```

This can be resolved if I remove and add the `Injector Component` to any provider GOs.

Although there may be other cases that cause this issue, I've noticed **this Unity editor Injector issue will reliably occur following an Android build**.

**Comment by mattvr** [comment]
Thanks for filing this issue. 

Can you try the [unitypackage from the 1.1.1 branch](https://github.com/mfav/syrinj/blob/1.1.1/Syrinj.unitypackage) and tell me if this fixes the error you're encountering?

Thanks!

**Comment by rhysp** [comment]
Confirmed the issue doesn't arise post-Android build on `1.1.1`, thank you!
